theme: jekyll-theme-minimal
<<<<<<< HEAD
title: [Alicia Lee's Portfolio]
<<<<<<< HEAD
description: [Hello! I am a Sophomore at Wellesley College majoring in Computer Science and minoring in Psychology.]
=======
description: [Hello! I am a Sophomore at Wellesley College majoring in Computer Science and minoring in Psychology.]


>>>>>>> b3cb3e2371e4ca453506b8d21f752f86862f4bff
=======
title: [Alicia Lee Portfolio]
description: [Hello! I am a Sophomore at Wellesley College majoring in Computer Science and minoring in Psychology.]
>>>>>>> def3c00a1c7bb71541c86cd5ef248f41e4f29d0b
