theme: jekyll-theme-minimal
title: [Alicia Lee's Portfolio]
description: [Hello! I am a Sophomore at Wellesley College majoring in Computer Science and minoring in Psychology.]
logo: [aliciajlee.github.io/img/IMG_8391 (1).jpg]
